/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prolog;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import org.jpl7.Query;
/**
 *
 * @author Dulce Bick
 */
public class Horoscopo extends javax.swing.JFrame {

    /**
     * Creates new form Horoscopo
     */
    public Horoscopo() {
        initComponents();
        setTitle("Obten tu signo");
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/nana.jpg"));
        setIconImage(icon);
    }
 private JLabel etiqueta;   
    

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jla = new javax.swing.JLabel();
        dia = new javax.swing.JTextField();
        mes = new javax.swing.JTextField();
        dime = new javax.swing.JButton();
        resultado = new javax.swing.JLabel();
        jla1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        imagen = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        img = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jla.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jla.setForeground(new java.awt.Color(255, 255, 255));
        jla.setText("No. Mes:");
        getContentPane().add(jla);
        jla.setBounds(30, 300, 110, 30);

        dia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diaActionPerformed(evt);
            }
        });
        dia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                diaKeyTyped(evt);
            }
        });
        getContentPane().add(dia);
        dia.setBounds(150, 260, 100, 30);

        mes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mesActionPerformed(evt);
            }
        });
        mes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mesKeyTyped(evt);
            }
        });
        getContentPane().add(mes);
        mes.setBounds(150, 300, 100, 30);

        dime.setBackground(new java.awt.Color(102, 255, 255));
        dime.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        dime.setText("Dime mi signo");
        dime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dimeActionPerformed(evt);
            }
        });
        getContentPane().add(dime);
        dime.setBounds(30, 340, 200, 31);

        resultado.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        resultado.setForeground(new java.awt.Color(255, 255, 255));
        resultado.setText("Signo");
        resultado.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                resultadoComponentAdded(evt);
            }
        });
        getContentPane().add(resultado);
        resultado.setBounds(250, 330, 300, 40);

        jla1.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jla1.setForeground(new java.awt.Color(255, 255, 255));
        jla1.setText("Día:");
        getContentPane().add(jla1);
        jla1.setBounds(80, 250, 70, 40);

        jButton1.setBackground(new java.awt.Color(102, 102, 255));
        jButton1.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jButton1.setText("Mi horoscopo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(420, 13, 210, 30);

        jButton2.setBackground(new java.awt.Color(204, 102, 255));
        jButton2.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jButton2.setText("Mi compatibilidad");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(420, 50, 210, 30);
        getContentPane().add(imagen);
        imagen.setBounds(450, 104, 210, 270);

        jButton3.setBackground(new java.awt.Color(102, 102, 255));
        jButton3.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jButton3.setText("Dime todo");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(30, 20, 140, 30);

        img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/NanaCalistar-canal_tuyubi_nueva_.jpg"))); // NOI18N
        getContentPane().add(img);
        img.setBounds(0, 0, 680, 390);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void diaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diaActionPerformed
     
        
          
        // TODO add your handling code here:
    }//GEN-LAST:event_diaActionPerformed

    private void mesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mesActionPerformed

    private void diaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_diaKeyTyped

           char car = evt.getKeyChar();
        if( dia.getText().length()>=2 ) evt.consume();
        if(( car<'0' || car>'9' )) evt.consume();

        // TODO add your handling code here:
    }//GEN-LAST:event_diaKeyTyped

    private void mesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mesKeyTyped

       char car = evt.getKeyChar();
        if( mes.getText().length()>=2 ) evt.consume();
        if(( car<'0' || car>'9' )) evt.consume();


        // TODO add your handling code here:
    }//GEN-LAST:event_mesKeyTyped

    private void dimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dimeActionPerformed

        int day = Integer.parseInt(dia.getText());
        int month = Integer.parseInt(mes.getText());
       
         
           try {
            String conexion = "consult('horoscopo.pl')";
            Query con = new Query(conexion);
            System.out.println(conexion + "" + (con.hasMoreSolutions() ? "ACEPTADO" : "FALLADO"));
            System.out.println("Iniciando la prueba");
        
            String consul = "signo("+this.dia.getText()+","+mes.getText()+",Z).";
            Query ejecutar = new Query(consul);
            if (ejecutar.hasSolution()) {
            
                System.out.println(" Tu horóscopo es: "+ejecutar.oneSolution().get("Z").toString());
                resultado.setText(String.valueOf(ejecutar.oneSolution().get("Z").toString()));
               // sign.setText(String.valueOf(ejecutar.oneSolution().get("Z,W,Q").toString()));
              switch(resultado.getText()){
                    
                case "sagitario":
                   String path = "/img/sagitario.gif";  
                   URL url = this.getClass().getResource(path);  
                   ImageIcon icon = new ImageIcon(url);   
                   imagen.setIcon(icon);  
                     System.out.println("Hola sagitario");  
               
                    break;
                   
                case "tauro":
                   String path2 = "/img/tauro.gif";  
                   URL url2 = this.getClass().getResource(path2);  
                   ImageIcon icon2 = new ImageIcon(url2);   
                   imagen.setIcon(icon2);  
                      System.out.println("Hola tauro");
                      
                      break;
                 
                case "virgo":
                   String path3 = "/img/virgo.gif";  
                   URL url3 = this.getClass().getResource(path3);  
                   ImageIcon icon3 = new ImageIcon(url3);   
                   imagen.setIcon(icon3);
                          System.out.println("Hola virgo");  
                     break;
                     
                case "cancer":
                   String path4 = "/img/cancer.gif";  
                   URL url4 = this.getClass().getResource(path4);  
                   ImageIcon icon4 = new ImageIcon(url4);   
                   imagen.setIcon(icon4);
                          System.out.println("Hola cancer");  
                      break;
                case "piscis":
                  String path5 = "/img/picis .gif";  
                   URL url5 = this.getClass().getResource(path5);  
                   ImageIcon icon5 = new ImageIcon(url5);   
                   imagen.setIcon(icon5);
                          System.out.println("Hola psisi");  
                      break;
                case "libra":
                     String path6 = "/img/libra.gif";  
                   URL url6 = this.getClass().getResource(path6);  
                   ImageIcon icon6 = new ImageIcon(url6);   
                   imagen.setIcon(icon6);
                          System.out.println("Hola libra");  
                      break;
                case "escorpio":
                     String path7 = "/img/escorpion.gif";  
                   URL url7 = this.getClass().getResource(path7);  
                   ImageIcon icon7 = new ImageIcon(url7);   
                   imagen.setIcon(icon7);
                          System.out.println("Hola escorpio");  
                      break;
                case "capricornio":
                     String path8 = "/img/capricornio.gif";  
                   URL url8 = this.getClass().getResource(path8);  
                   ImageIcon icon8 = new ImageIcon(url8);   
                   imagen.setIcon(icon8);
                          System.out.println("Hola capricornio");  
                      break;
                case "leo":
                     String path9 = "/img/leo.gif";  
                   URL url9 = this.getClass().getResource(path9);  
                   ImageIcon icon9 = new ImageIcon(url9);   
                   imagen.setIcon(icon9);
                          System.out.println("Hola leo");  
                      break;
                case "geminis":
                     String path10 = "/img/geminis.gif";  
                   URL url10 = this.getClass().getResource(path10);  
                   ImageIcon icon10= new ImageIcon(url10);   
                   imagen.setIcon(icon10);
                          System.out.println("Hola geminis");  
                      break;
                case "acuario":
                     String path11 = "/img/acuario.gif";  
                   URL url11 = this.getClass().getResource(path11);  
                   ImageIcon icon11 = new ImageIcon(url11);   
                   imagen.setIcon(icon11);
                          System.out.println("Hola acuario");  
                      break;
              
                case "aries":
                     String path12 = "/img/aries.gif";  
                   URL url12 = this.getClass().getResource(path12);  
                   ImageIcon icon12 = new ImageIcon(url12);   
                   imagen.setIcon(icon12);
                        System.out.println("Hola aries");  
                      break;
              
              }
            
              
             
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
           
      
       
 
           

        // TODO add your handling code here:
    }//GEN-LAST:event_dimeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   dime o= new dime();
   o.setBounds(500,100,686,510);
   o.setVisible(true);
   this.setVisible(false);
   o.setResizable(false);


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void resultadoComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_resultadoComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_resultadoComponentAdded

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
   Compatible o = new Compatible();
   o.setBounds(500,100,654,370);
   o.setVisible(true);
   this.setVisible(false);
   o.setResizable(false);




        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
           Todo a = new Todo();
           a.setBounds(500,100,680,500);
           a.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Horoscopo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Horoscopo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Horoscopo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Horoscopo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Horoscopo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dia;
    private javax.swing.JButton dime;
    private javax.swing.JLabel imagen;
    private javax.swing.JLabel img;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jla;
    private javax.swing.JLabel jla1;
    private javax.swing.JTextField mes;
    private javax.swing.JLabel resultado;
    // End of variables declaration//GEN-END:variables
}
