/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prolog;
import org.jpl7.Query;
/**
 *
 * @author Dulce Bick
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        num2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        num1 = new javax.swing.JTextField();
        resultado = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        sumar = new javax.swing.JButton();
        resta = new javax.swing.JButton();
        multiplica = new javax.swing.JButton();
        divide = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Número 1:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(150, 130, 60, 14);

        jLabel2.setText("Mini Calculdora");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(160, 90, 130, 30);

        num2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num2ActionPerformed(evt);
            }
        });
        getContentPane().add(num2);
        num2.setBounds(240, 160, 60, 20);

        jLabel3.setText("Número 2:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(150, 150, 60, 14);

        num1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num1ActionPerformed(evt);
            }
        });
        getContentPane().add(num1);
        num1.setBounds(240, 130, 59, 20);

        resultado.setText("0");
        getContentPane().add(resultado);
        resultado.setBounds(250, 250, 40, 30);

        jLabel4.setText("Resultado");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(170, 260, 60, 14);

        sumar.setText("sumar");
        sumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumarActionPerformed(evt);
            }
        });
        getContentPane().add(sumar);
        sumar.setBounds(260, 190, 90, 23);

        resta.setText("Restar");
        resta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restaActionPerformed(evt);
            }
        });
        getContentPane().add(resta);
        resta.setBounds(260, 220, 90, 23);

        multiplica.setText("multiplica");
        multiplica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplicaActionPerformed(evt);
            }
        });
        getContentPane().add(multiplica);
        multiplica.setBounds(130, 190, 120, 23);

        divide.setText("Divide");
        divide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divideActionPerformed(evt);
            }
        });
        getContentPane().add(divide);
        divide.setBounds(130, 220, 120, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void num2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_num2ActionPerformed

    private void num1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_num1ActionPerformed

    private void sumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumarActionPerformed
        int uno = Integer.parseInt(num1.getText());
        int dos = Integer.parseInt(num2.getText());
         //resultado.setText(String.valueOf(uno+dos));
         
           try {
            String conexion = "consult('ejericio1.pl')";
            Query con = new Query(conexion);
            System.out.println(conexion + "" + (con.hasMoreSolutions() ? "ACEPTADO" : "FALLADO"));
            System.out.println("Iniciando la Suma");
           //String consulta="bisabuelo(pedro,Y)";
           // String consul="suma(A,B,C)";
            String consul = "suma("+this.num1.getText()+","+num2.getText()+",C).";
            Query ejecutar = new Query(consul);
            if (ejecutar.hasSolution()) {
                //this.resultado.append("-----\n");
                System.out.println("La suma es : "+ejecutar.oneSolution().get("C").toString());
                resultado.setText(String.valueOf(ejecutar.oneSolution().get("C").toString()));
               // resultado.setText(String.valueOf(uno+dos));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
   

    }//GEN-LAST:event_sumarActionPerformed

    private void multiplicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplicaActionPerformed

int uno = Integer.parseInt(num1.getText());
        int dos = Integer.parseInt(num2.getText());
         //resultado.setText(String.valueOf(uno+dos));
         
           try {
            String conexion = "consult('ejericio1.pl')";
            Query con = new Query(conexion);
            System.out.println(conexion + "" + (con.hasMoreSolutions() ? "ACEPTADO" : "FALLADO"));
            System.out.println("Iniciando la multiplicación");
           //String consulta="bisabuelo(pedro,Y)";
           // String consul="suma(A,B,C)";
            String consul = "multiplica("+this.num1.getText()+","+num2.getText()+",C).";
            Query ejecutar = new Query(consul);
            if (ejecutar.hasSolution()) {
                //this.resultado.append("-----\n");
                System.out.println("La multiplicación  es : "+ejecutar.oneSolution().get("C").toString());
                resultado.setText(String.valueOf(ejecutar.oneSolution().get("C").toString()));
               // resultado.setText(String.valueOf(uno+dos));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_multiplicaActionPerformed

    private void restaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restaActionPerformed

int uno = Integer.parseInt(num1.getText());
        int dos = Integer.parseInt(num2.getText());
         //resultado.setText(String.valueOf(uno+dos));
         
           try {
            String conexion = "consult('ejericio1.pl')";
            Query con = new Query(conexion);
            System.out.println(conexion + "" + (con.hasMoreSolutions() ? "ACEPTADO" : "FALLADO"));
            System.out.println("Iniciando la resta");
           //String consulta="bisabuelo(pedro,Y)";
           // String consul="suma(A,B,C)";
            String consul = "resta("+this.num1.getText()+","+num2.getText()+",C).";
            Query ejecutar = new Query(consul);
            if (ejecutar.hasSolution()) {
                //this.resultado.append("-----\n");
                System.out.println("La resta es : "+ejecutar.oneSolution().get("C").toString());
                resultado.setText(String.valueOf(ejecutar.oneSolution().get("C").toString()));
               // resultado.setText(String.valueOf(uno+dos));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_restaActionPerformed

    private void divideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divideActionPerformed

int uno = Integer.parseInt(num1.getText());
        int dos = Integer.parseInt(num2.getText());
         //resultado.setText(String.valueOf(uno+dos));
         
           try {
            String conexion = "consult('ejericio1.pl')";
            Query con = new Query(conexion);
            System.out.println(conexion + "" + (con.hasMoreSolutions() ? "ACEPTADO" : "FALLADO"));
            System.out.println("Iniciando la división");
           //String consulta="bisabuelo(pedro,Y)";
           // String consul="suma(A,B,C)";
            String consul = "divide("+this.num1.getText()+","+num2.getText()+",C).";
            Query ejecutar = new Query(consul);
            if (ejecutar.hasSolution()) {
                //this.resultado.append("-----\n");
                System.out.println("La división  es : "+ejecutar.oneSolution().get("C").toString());
                resultado.setText(String.valueOf(ejecutar.oneSolution().get("C").toString()));
               // resultado.setText(String.valueOf(uno+dos));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_divideActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton divide;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton multiplica;
    private javax.swing.JTextField num1;
    private javax.swing.JTextField num2;
    private javax.swing.JButton resta;
    private javax.swing.JLabel resultado;
    private javax.swing.JButton sumar;
    // End of variables declaration//GEN-END:variables
}
