/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prolog;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import org.jpl7.Query;
/**
 *
 * @author Dulce Bick
 */
public class Opcion extends javax.swing.JFrame {

    /**
     * Creates new form Opcion
     */
    public Opcion() {
        initComponents();
        setTitle("Obten tu horoscopo");
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/nana.jpg"));
        setIconImage(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        ver = new javax.swing.JButton();
        horos = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        area = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jButton1.setText("Menú");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(30, 210, 150, 27);

        ver.setBackground(new java.awt.Color(255, 204, 255));
        ver.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        ver.setText("Ver mi horoscopo");
        ver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verActionPerformed(evt);
            }
        });
        getContentPane().add(ver);
        ver.setBounds(10, 340, 190, 40);

        horos.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        horos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horosActionPerformed(evt);
            }
        });
        horos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                horosKeyTyped(evt);
            }
        });
        getContentPane().add(horos);
        horos.setBounds(30, 290, 150, 30);

        area.setColumns(20);
        area.setFont(new java.awt.Font("Microsoft YaHei", 1, 13)); // NOI18N
        area.setRows(5);
        jScrollPane1.setViewportView(area);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(240, 270, 380, 140);

        jButton2.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jButton2.setText("Compatibilidad");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(30, 250, 150, 27);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/HOROSCOPOS (2).png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-60, -10, 780, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

           Horoscopo a = new Horoscopo();
            a.setBounds(500,100,660,420);
            a.setResizable(false);
            a.setVisible(true);
            this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void horosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_horosKeyTyped

  char car = evt.getKeyChar(); 
if((car<'a' || car>'z'))
{
evt.consume();
    
}else{
  //  z.setText(z.getText()+String.valueOf(evt.getKeyChar()));
}


        // TODO add your han
    }//GEN-LAST:event_horosKeyTyped

    private void verActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verActionPerformed
  
         String sig = String.valueOf(horos.getText());
           
           System.out.println(sig);
         
          try {
            String conexion = "consult('horoscopo.pl')";
            Query con = new Query(conexion);
            System.out.println(conexion + "" + (con.hasMoreSolutions() ? "ACEPTADO" : "FALLADO"));
            System.out.println("Iniciando la prueba");
            String consul = "prueba2("+sig+",Y).";
            Query ejecutar = new Query(consul);
            if (ejecutar.hasSolution()) {
           
           System.out.println(" Tu horóscopo es: "+ejecutar.oneSolution().get("Y").toString());
           
           area.setText(String.valueOf(ejecutar.oneSolution().get("Y").toString()));
           
             
             
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
           
                    
          
        // TODO add your handling code here:
    }//GEN-LAST:event_verActionPerformed

    private void horosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horosActionPerformed




        // TODO add your handling code here:
    }//GEN-LAST:event_horosActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

 Compatible o = new Compatible();
   o.setBounds(500,100,654,370);
   o.setVisible(true);
   this.setVisible(false);
   o.setResizable(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Opcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Opcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Opcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Opcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Opcion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area;
    private javax.swing.JFormattedTextField horos;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton ver;
    // End of variables declaration//GEN-END:variables
}
